// Date: 10/12/2014 3:08:12 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelStorageJar extends ModelBase
{
  //fields
    ModelRenderer Lid;
    ModelRenderer Base;
    ModelRenderer Wall;
    ModelRenderer Wall;
    ModelRenderer Wall;
    ModelRenderer Wall;
    ModelRenderer Cap;
  
  public ModelStorageJar()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Lid = new ModelRenderer(this, 0, 16);
      Lid.addBox(0F, 0F, 0F, 8, 1, 8);
      Lid.setRotationPoint(-4F, 11F, -4F);
      Lid.setTextureSize(64, 64);
      Lid.mirror = true;
      setRotation(Lid, 0F, 0F, 0F);
      Base = new ModelRenderer(this, 24, 0);
      Base.addBox(0F, 0F, 0F, 10, 1, 10);
      Base.setRotationPoint(-5F, 23F, -5F);
      Base.setTextureSize(64, 64);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Wall = new ModelRenderer(this, 0, 32);
      Wall.addBox(0F, 0F, 0F, 10, 12, 1);
      Wall.setRotationPoint(-5F, 11F, 4F);
      Wall.setTextureSize(64, 64);
      Wall.mirror = true;
      setRotation(Wall, 0F, 0F, 0F);
      Wall = new ModelRenderer(this, 0, 32);
      Wall.addBox(0F, 0F, 0F, 10, 12, 1);
      Wall.setRotationPoint(-5F, 11F, -5F);
      Wall.setTextureSize(64, 64);
      Wall.mirror = true;
      setRotation(Wall, 0F, 0F, 0F);
      Wall = new ModelRenderer(this, 32, 32);
      Wall.addBox(0F, 0F, 0F, 1, 12, 8);
      Wall.setRotationPoint(-5F, 11F, -4F);
      Wall.setTextureSize(64, 64);
      Wall.mirror = true;
      setRotation(Wall, 0F, 0F, 0F);
      Wall = new ModelRenderer(this, 32, 32);
      Wall.addBox(0F, 0F, 0F, 1, 12, 8);
      Wall.setRotationPoint(4F, 11F, -4F);
      Wall.setTextureSize(64, 64);
      Wall.mirror = true;
      setRotation(Wall, 0F, 0F, 0F);
      Cap = new ModelRenderer(this, 0, 0);
      Cap.addBox(0F, 0F, 0F, 4, 2, 4);
      Cap.setRotationPoint(-2F, 9F, -2F);
      Cap.setTextureSize(64, 64);
      Cap.mirror = true;
      setRotation(Cap, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Lid.render(f5);
    Base.render(f5);
    Wall.render(f5);
    Wall.render(f5);
    Wall.render(f5);
    Wall.render(f5);
    Cap.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
